# Spring configurations
spring:
  threads:
    virtual: 
      enabled: true # since JDK 21 LTS supported. Can reduce memory consumption and response time in high-traffic scenarios
  profiles: # important!
    active: "oidc"
  security:
    oauth2: # Remove this from the configuration (it is just an example) to avoid that this is leaked to the code repository and inject them dyamically during runtime. See: https://codeberg.org/ZuInnoTe/spring-boot-angular-example/src/branch/main/container/scripts/run-app.sh
      client:
        registration: 
          oidcidp: 
            client-id: <client-id>  # Do not store in version repository - inject them dynamically during runtime
            client-secret: <secret> # Do not store in version repository - inject them dynamically during runtime
        provider:
           oidcidp:
            issuer-uri: <issuer-uri> # idp metadata uri for auto-configuration. See https://docs.spring.io/spring-security/reference/servlet/oauth2/login/core.html#oauth2login-sample-application-config 
logging:
    level:
        root: "warn"
        org.springframework.web: "info"
        org.hibernate: "error"
# Server
server:
  ssl:
    enabled-protocols: TLSv1.3
    ciphers: TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256
# Application configurations
application:
     oidc:
        mapper: # map jwt claims to Spring Security authorities
            jwtRoleClaims: ["scope","scp"] # JWT claims that contain authorities
            authoritiesPrefix: "SCOPE_" # Prefix for Spring Security Authorities
     https:
        headers:
          permissionPolicy: "accelerometer=(),  autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(),  encrypted-media=(),  fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(),  payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(),  hid=(), idle-detection=(), serial=(),  window-placement=()"
          csp: "default-src 'none'; base-uri 'self'; script-src 'unsafe-inline' 'self'; style-src 'self' 'unsafe-inline'; img-src 'self'; connect-src 'self'; font-src 'self'; object-src 'none'; media-src 'none'; child-src 'self'; form-action 'self'; frame-ancestors 'none'; navigate-to 'self'; block-all-mixed-content; trusted-types angular; require-trusted-types-for 'script';"
          referrerPolicy: "no-referrer" # possible values: https://github.com/spring-projects/spring-security/blob/main/web/src/main/java/org/springframework/security/web/header/writers/ReferrerPolicyHeaderWriter.java#L101
          coep: "require-corp; report-to=\"default\""
          coop: "same-origin; report-to=\"default\""
          corp: "same-origin"