# Spring configurations
spring:
  threads:
    virtual: 
      enabled: true # since JDK 21 LTS supported. Can reduce memory consumption and response time in high-traffic scenarios
  profiles: # important - select the right profiles for your environment
    active: "dev" # "dev" is only for development purposes! Not in production
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    driverClassName: org.h2.Driver
    hikari:
        maximum-pool-size: 10 # have a reasonable low number: https://github.com/brettwooldridge/HikariCP/wiki/About-Pool-Sizing
  jackson:
       serialization:
           FAIL_ON_EMPTY_BEANS: false # for returning directly objects returned by JPA
  jpa:
    defer-datasource-initialization: true # only for testing to load test data
    hibernate:
      ddl-auto: create
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    properties:
      hibernate:
         enable_lazy_load_no_trans: true # EXPERIMENTAL FOR LAZY LOADING MIGHT NEED TO BE REMOVED AND REPLACED WITH A MORE FINETUNED EAGER VS LAZY
         jdbc:
           batch_size: 20
         order_inserts: true
         order_updates: true
         globally_quoted_identifiers: true
         javax:
            cache:
               provider: org.ehcache.jsr107.EhcacheCachingProvider
         cache:
            use_second_level_cache: true
            use_query_cache: true
            region:
                 factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
  h2: # only for testing purposes
    console.enabled: true
logging:
    level:
        root: "warn"
        org.springframework.web: "info"
        org.hibernate: "info"
# Application configurations
application:
     https:
        headers:
          permissionPolicy: "accelerometer=(),  autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(),  encrypted-media=(),  fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(),  payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(),  hid=(), idle-detection=(), serial=(),  window-placement=()"
          csp: "default-src 'none'; base-uri 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; font-src 'self'; object-src 'none'; media-src 'none'; child-src 'self'; form-action 'self'; frame-ancestors 'none'; navigate-to 'self'; upgrade-insecure-requests; trusted-types angular; require-trusted-types-for 'script';" # minimal policy working with current Angular - to be reviewed in newer Angular versions
          referrerPolicy: "no-referrer" # possible values: https://github.com/spring-projects/spring-security/blob/main/web/src/main/java/org/springframework/security/web/header/writers/ReferrerPolicyHeaderWriter.java#L101
          coep: "require-corp; report-to=\"default\""
          coop: "same-origin; report-to=\"default\""
          corp: "same-origin"